name: Gradle Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK 16
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'gradle'
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew build --stacktrace
          ./gradlew shadowJar
      - name: Move the artifact
        run: |
          mkdir staging
          mv build staging/build
          mv v4/build staging/v4
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Package
          path: staging
