name: Gradle Build
on: [ push, pull_request ]

jobs:
  build:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '17'
      package-name: BoxMigrator-Build-${{ github.run_number }}
      artifact-directory: "./build/libs"
